#!/usr/bin/env bash
cd "$(dirname "$0")"
PORT="${1:-8765}"
echo ""
echo "Yoga Soul Festival — server locale"
echo "  http://localhost:${PORT}/"
echo ""
echo "Pagine disponibili:"
echo "  /index.html      Home"
echo "  /programma.html  Programma"
echo "  /artisti.html    Artisti"
echo "  /biglietti.html  Biglietti"
echo "  /vendors.html    Vendors"
echo "  /faq.html        FAQ"
echo ""
echo "Premi Ctrl+C per fermare."
echo ""
python3 -m http.server "$PORT"
